version: '3'

services:
  postgres:
    image: 'postgres:latest'
    environment:
     - "POSTGRES_PASSWORD=1234"
    networks:
      - net
  redis:
    image: 'redis:latest'
    networks:
      - net
  nginx:
    depends_on:
      - april
      - client
    restart: always
    container_name: nginx
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
    networks:
      - net
  april:
    depends_on:
      - postgres
    container_name: april
    build:
      dockerfile: Dockerfile.dev
      context: ./contain
    volumes:
      - "$PWD/contain:/app"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    networks:
      - net
  client:
    container_name: client
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - "$PWD/client:/app"
    networks:
      - net 
  worker:
    container_name: worker
    environment:
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - "$PWD/worker:/app"
    networks:
      - net
networks:
   net:
